apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: percona
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: mysql-db
spec:
  type: LoadBalancer
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/component: proxysql
    app.kubernetes.io/instance: cluster1
    app.kubernetes.io/name: percona-xtradb-cluster
